# Generated by Django 3.0.6 on 2020-06-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
