# Generated by Django 3.0.6 on 2020-05-30 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='singer',
            managers=[
            ],
        ),
    ]
