# Generated by Django 3.0.6 on 2020-05-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imgintroduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=50)),
                ('img_description', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
    ]
